[package]
name = "badapple"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
imageproc = "0.26.0"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
